{{- if .Values.certManager.enabled }}
{{- $dnsNames := .Values.certManager.dnsNames }}
{{- if eq (len $dnsNames) 0 }}
{{- $dnsNames = list .Values.config.server.hostname }}
{{- end }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.certManager.certificateName }}
  labels:
    {{- include "stalwart.labels" . | nindent 4 }}
spec:
  secretName: {{ .Values.certManager.secretName }}
  issuerRef:
    name: {{ .Values.certManager.issuerName }}
    kind: {{ .Values.certManager.issuerKind }}
    group: {{ .Values.certManager.issuerGroup }}
  dnsNames:
    {{- range $dnsNames }}
    - {{ . | quote }}
    {{- end }}
{{- end }}
