apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: stalwart
  namespace: stalwart
spec:
  interval: 30m
  releaseName: stalwart
  chart:
    spec:
      chart: antigenic-stalwart-helm-chart
      version: 1.0.4
      sourceRef:
        kind: HelmRepository
        name: antigenic-stalwart
        namespace: flux-system
  install:
    createNamespace: true
  values:
    replicaCount: 3

    secret:
      create: false
      name: stalwart-secrets
    certManager:
      enabled: true
      issuerName: letsencrypt-dns
      secretName: stalwart-mail-tls

    config:
      server:
        hostname: mail.example.com
      http:
        useXForwarded: false
      postgresql:
        host: postgres-rw.database.svc.cluster.local
        database: stalwart
        user: stalwart
      s3:
        endpoint: https://minio.storage.svc.cluster.local:9000
        bucket: stalwart
      meilisearch:
        url: http://meilisearch.search.svc.cluster.local:7700
